development:
  adapter: postgresql
  encoding: utf8
  database: gramr_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gramr_test
  pool: 5
  username:
  password:

production:
  encoding: utf8
  pool: 5

cucumber:
  <<: *TEST
